version: '3.8'
services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "4173:4173"
    container_name: frontend
    depends_on:
      - backend
    networks:
      - socket_network
  backend:
    build: ./backend
    restart: always
    ports:
      - "5050:3002"
    container_name: backend
    networks:
      - socket_network
networks:
  socket_network:
    driver: bridge
  